name: Check heredoc syntax
on: [push]
jobs:
  print-envs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          START_RUNNER_JSON="/home/runner/work/_temp/start-runner.json"
          echo <<EOF > "$START_RUNNER_JSON"
          {
            "result": "skipped",
            "outputs": {}
          }
          EOF
          echo "entries=$(cat \"$START_RUNNER_JSON\")" >> $GITHUB_OUTPUT
