name: workflow-call
on:
  workflow_call:
    inputs:
      bool_input:
        type: boolean
        description: "BOOL"
        default: true
      string_input:
        type: string
        description: "STRING"
        required: true
jobs:
  tasks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        entry:
          - task: "X"
            extra_key: "A"
          - task: "Y"
          - task: "Z"
    steps:
      - name: Print variables
        run: |
          echo inputs = ${{ inputs }}
          echo inputs.bool_input = ${{ inputs.bool_input }}
          echo inputs.string_input = ${{ inputs.string_input }}
          echo "inputs.string_input != ''" = ${{ inputs.string_input != '' }}
          echo "inputs.bool_input && inputs.string_input" = ${{ inputs.bool_input && inputs.string_input }}
          echo matrix.entry = ${{ matrix.entry }}
          echo matrix.entry.task = ${{ matrix.entry.task }}
          echo matrix.entry.extra_key = ${{ matrix.entry.extra_key }}
      - name: Run if "inputs.string_input != '' && matrix.entry.task != ''"
        run: echo OK
        if: ${{ inputs.string_input != '' && matrix.entry.extra_key != '' }}


