name: Check matrix
on: [workflow_dispatch]
jobs:
  output-x:
    runs-on: ubuntu-latest
    outputs:
      runs-on: ${{ steps.echo.outputs.runs-on }}
    steps:
    - id: echo
      run: echo '::set-output name=runs-on::ubuntu-latest'
  needs-x:
    needs: [output-x]
    strategy:
      matrix:
        entry:
        - runs-on: ${{ needs.output-x.outputs.runs-on }}
    if: ${{ matrix.entry.runs-on != "" }}
    runs-on: ${{ matrix.entry.runs-on }}
    steps:
    - run: echo "Hello"
    - run: echo matrix.entry.runs-on=${{ matrix.entry.runs-on }}
