name: Check needs
on: [push]
jobs:
  dep-x:
    runs-on: ubuntu-latest
    if: false
    steps:
    - run: echo "Hello"
  needs-y:
    runs-on: ubuntu-latest
    needs: [needs-x]
    steps:
    - run: echo "Late Hello"

  needs-x:
    runs-on: ubuntu-latest
    needs: [dep-x]
    if: ${{ always() }}
    steps:
    - run: echo "Hello"
    - run: echo "needs.dep-x.result=${{ needs.dep-x.result }}"
