name: Check needs
on: [push]
jobs:
  dep-x:
    runs-on: ubuntu-latest
    if: false
    steps:
    - run: echo "Hello"
  needs-x:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        entry:
        - needs: [dep-x]
        - needs: []
    needs: ${{ matrix.entry.needs }}
    steps:
    - run: echo "Hello"
