name: Check needs
on: [push]
jobs:
  dep-x:
    runs-on: ubuntu-latest
    if: false
    steps:
    - run: echo "Hello"
  needs-x:
    strategy:
      matrix:
        entry:
        - needs: [dep-x]
          runs-on: ubuntu-latest
        - needs: []
          runs-on: ubuntu-latest
    runs-on: ${{ matrix.entry.runs-on }}
    needs: ${{ matrix.entry.needs }}
    steps:
    - run: echo "Hello"
