name: Check Secret Variables
on: [workflow_dispatch]
jobs:
  print-envs:
    runs-on: ubuntu-18.04
    steps:
      - name: Print secrets
        run: |
          set -x
          echo $GITHUB_TOKEN
          echo $SECRET_VALUE1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SECRET_VALUE1: ${{ secrets.SECRET_VALUE1 }}
