name: Check swiftwasm/swiftwasm-action

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
      - uses: swiftwasm/swiftwasm-action@v5.8
        with:
          shell-action: swift --version
