name: Trigger inputs2
on: [workflow_dispatch]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - run: gh workflow run env.yaml -R ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

