name: Check artifact
on: [workflow_dispatch]
jobs:
  upload:
    runs-on: ubuntu-20.04
    steps:
      - run: echo Hello > hello.txt
      - run: echo Yay > yay.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello-txt
          path: hello.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: yay-txt
          path: yay.txt
  download:
    needs: [upload]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: release
      - run: tree
